name: Capturing Outputs Example Workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.set_output.outputs.my_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command and set output
        id: set_output
        run: |
          echo "Running a date command..."
          MY_OUTPUT=$(date) # Example command to get the current date and time
          #echo "my_output=$MY_OUTPUT" >> $GITHUB_ENV
          echo "::set-output name=my_output::$MY_OUTPUT"

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the output from first job
        run: |
          echo "The output from the first job is: ${{ needs.first_job.outputs.my_output }}"
